package saferis

import zio.Chunk

import scala.annotation.StaticAnnotation

/** Represents a label for a column in a result set. Fields in a case class can be annotated with this to specify the
  * column name/label Example:
  * {{{
  *   case class User(
  *     @label("user_id") id: Int,
  *     @label("user_name") name: String
  *   )
  * }}}
  *
  * @param name
  */
final case class label(name: String) extends StaticAnnotation

/** denotes fields of a case class that are generated by the database
  */
class generated extends key

/** denotes fields of a case class that make up a primary key
  */
class key extends StaticAnnotation

/** Represents a column/field in result set
  *
  * @param name
  *   the scala field name in the case class
  * @param label
  *   the column name/label in the result set
  */
final case class Column[R](
    name: String,
    label: String,
    isKey: Boolean,
    isGenerated: Boolean,
    isNullable: Boolean,
    defaultValue: Option[R],
    tableAlias: Option[Alias],
)(using readable: Decoder[R], writable: Encoder[R])
    extends Placeholder:
  type ColumnType = R
  override val sql: String        = tableAlias.fold(label)(a => s"${a.value}.$label")
  val pieces: Chunk[SqlPiece]     = Chunk(SqlPiece.Text(sql))
  val issues: List[FragmentIssue] = Nil

  def pgType: PgType = writable.pgType

  private[saferis] def read(row: SqlRow): Either[SaferisError, (String, R)] =
    def fail(detail: String) = Left(SaferisError.DecodingError(label, pgType.toString, detail))
    row.get(label) match
      case Left(err)    => fail(err.detail)
      case Right(value) =>
        readable.decode(value) match
          case Left(err)      => fail(err.detail)
          case Right(decoded) => Right(name -> decoded)

  private[saferis] def withTableAlias(alias: Option[Alias]): Column[R] = copy(tableAlias = alias)

  private[saferis] def columnType(using Dialect): String = writable.columnType

  /** Returns the DEFAULT clause for DDL if a default value is defined */
  private[saferis] def defaultClause: Option[String] =
    defaultValue.map(v => s"default ${writable.literal(v)}")
end Column
