package saferis.h2

import saferis.*

/** H2 dialect: SQL for H2 2.x in its native mode. Use it with `saferis.h2.jdbc.H2Jdbc`, typically for fast in-memory
  * tests of code that runs on another database in production.
  *
  * No array, `RETURNING`, or upsert capability is claimed: H2 spells those differently from the dialects that have
  * them, so membership renders `IN (...)`.
  */
object H2Dialect extends Dialect:
  val name: DialectName = DialectName("H2")

  /** H2 2.5.250 `Constants.MAX_NUMERIC_PRECISION` and `TypeInfo.TYPE_NUMERIC_FLOATING_POINT` (scale is half). */
  val NumericPrecision: Int = 100000
  val NumericScale: Int     = 50000

  /** True when `value` fits `numeric(100000, 50000)` without H2 rounding it. */
  def fitsNumeric(value: BigDecimal): Boolean =
    val stripped         = value.bigDecimal.stripTrailingZeros
    val scale            = stripped.scale
    val precision        = stripped.precision
    val integerDigits    = if scale < 0 then precision - scale else math.max(precision - scale, 0)
    val fractionalDigits = math.max(scale, 0)
    integerDigits <= NumericPrecision - NumericScale && fractionalDigits <= NumericScale

  def columnType(tpe: SqlType): ColumnType = ColumnType:
    tpe match
      case SqlType.Bool            => "boolean"
      case SqlType.SmallInt        => "smallint"
      case SqlType.Integer         => "integer"
      case SqlType.BigInt          => "bigint"
      case SqlType.Real            => "real"
      case SqlType.DoublePrecision => "double precision"
      case SqlType.Numeric         => "numeric(100000, 50000)"
      case SqlType.VarChar         => s"varchar($DefaultVarcharLength)"
      case SqlType.Text            => "character large object"
      case SqlType.Binary          => "varbinary"
      case SqlType.Date            => "date"
      case SqlType.Time            => "time(6)"
      case SqlType.TimeTz          => "time(6) with time zone"
      case SqlType.Timestamp       => "timestamp(6)"
      case SqlType.TimestampTz     => "timestamp(6) with time zone"
      case SqlType.Json            => "json"
      case SqlType.Uuid            => "uuid"
      case SqlType.Array(element)  => s"${columnType(element)} array"
      case SqlType.Other(_)        => "character large object"

  def generatedKey(key: GeneratedKey): SqlText = SqlText:
    key match
      case GeneratedKey.IdentityPrimaryKey => " generated by default as identity primary key"
      case GeneratedKey.Identity           => " generated by default as identity"
      case GeneratedKey.PrimaryKey         => " primary key"
      case GeneratedKey.Plain              => ""
end H2Dialect

// Export H2Dialect with its singleton type, like the other dialects.
given H2Dialect.type = H2Dialect
