package saferis.h2

import saferis.*

/** H2 dialect: SQL for H2 2.x in its native mode. Use it with `saferis.h2.jdbc.H2Jdbc`, typically for fast in-memory
  * tests of code that runs on another database in production.
  *
  * No array, `RETURNING`, or upsert capability is claimed: H2 spells those differently from the dialects that have
  * them, so membership renders `IN (...)`.
  */
object H2Dialect extends Dialect:
  val name: String = "H2"

  def columnType(tpe: SqlType): String = tpe match
    case SqlType.Bool           => "boolean"
    case SqlType.Int2           => "smallint"
    case SqlType.Int4           => "integer"
    case SqlType.Int8           => "bigint"
    case SqlType.Float4         => "real"
    case SqlType.Float8         => "double precision"
    case SqlType.Numeric        => "numeric(1000, 100)"
    case SqlType.VarChar        => s"varchar($DefaultVarcharLength)"
    case SqlType.Text           => "character large object"
    case SqlType.Bytea          => "varbinary"
    case SqlType.Date           => "date"
    case SqlType.Time           => "time(6)"
    case SqlType.Timestamp      => "timestamp(6)"
    case SqlType.Timestamptz    => "timestamp(6) with time zone"
    case SqlType.Jsonb          => "json"
    case SqlType.Uuid           => "uuid"
    case SqlType.Array(element) => s"${columnType(element)} array"
    case SqlType.Other(_)       => "character large object"

  def autoIncrementClause(isGenerated: Boolean, isPrimaryKey: Boolean, hasCompoundKey: Boolean): String =
    if isGenerated && isPrimaryKey && !hasCompoundKey then " generated by default as identity primary key"
    else if isGenerated then " generated by default as identity"
    else if isPrimaryKey && !hasCompoundKey then " primary key"
    else ""
end H2Dialect

// Export H2Dialect with its singleton type, like the other dialects.
given H2Dialect.type = H2Dialect
