addSbtPlugin("org.scalameta"     % "sbt-scalafmt"  % "2.6.1")
addSbtPlugin("rocks.earlyeffect" % "sbt-marklit"   % "0.1.0")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"  % "0.14.7")
addSbtPlugin("rocks.earlyeffect" % "sbt-dynver-ci" % "0.2.2")
addSbtPlugin("com.github.sbt"    % "sbt-pgp"       % "2.3.1")
addSbtPlugin("org.scoverage"     % "sbt-scoverage" % "2.4.4")
addSbtPlugin("rocks.earlyeffect" % "sbt-zipx"      % "0.0.12")
