// Generated by zipx. Do not edit. Run 'sbt zipxWorkflowGenerate' to regenerate.
resolvers += "central-snapshots" at "https://central.sonatype.com/repository/maven-snapshots/"
forceUpdatePeriod := Some(scala.concurrent.duration.Duration.Zero)
addSbtPlugin("rocks.earlyeffect" % "sbt-zipx" % "0.17.0-SNAPSHOT")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.6.2")
addSbtPlugin("rocks.earlyeffect" % "sbt-specular" % "0.17.0")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.14.7")
addSbtPlugin("rocks.earlyeffect" % "sbt-dynver-ci" % "0.2.3")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "2.4.4")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.22.0")
addSbtPlugin("org.scala-native" % "sbt-scala-native" % "0.5.12")
